services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php-app
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php-app:/var/www/html/
        ports:
            - 8000:80

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password123#@!
            MYSQL_DATABASE: php_db
            MYSQL_USER: jochemos
            MYSQL_PASSWORD: Password123#@!
        ports:
            - "9908:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - '8081:80'
        restart: always
        environment:
          PMA_HOST: db
        depends_on:
          - db
